### ISSUE TITLE
Cannot read property 'Constellation' of undefined

### ISSUE THREAD

**Issue by elie222** [JackAdams/constellation-autopublish#1]
I do Ctrl-M and meteor toys (constellation) pops up, and I click autopublish, which now changes from red to green, but nothing else happens after.

**Comment by elie222** [comment]
Just noticed the server logs. This was the real issue:

```
=> App running at: http://localhost:3000/
I20150714-16:25:48.303(3)? Exception from sub Constellation_autopublish id ZzgdmNXPN4KFxuhYz TypeError: Cannot read property 'Constellation' of undefined
I20150714-16:25:48.303(3)?     at packages/constellation:autopublish/autopublish-server.js:3:1
I20150714-16:25:48.303(3)?     at Array.reduce (native)
I20150714-16:25:48.303(3)?     at Function._.reduce._.foldl._.inject (packages/underscore/underscore.js:139:1)
I20150714-16:25:48.303(3)?     at [object Object].Package [as _handler] (packages/constellation:autopublish/autopublish-server.js:2:1)
I20150714-16:25:48.303(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150714-16:25:48.303(3)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150714-16:25:48.303(3)?     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks:unblock/lib/unblock.js:47:1)
I20150714-16:25:48.303(3)?     at [object Object].MeteorX.Session._startSubscription (packages/meteorhacks:unblock/lib/unblock.js:35:1)
I20150714-16:25:48.303(3)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150714-16:25:48.303(3)?     at [object Object].MeteorX.Session.protocol_handlers.sub (packages/meteorhacks:unblock/lib/unblock.js:9:1)
```

**Comment by JackAdams** [comment]
I notice you've got CTRL-M, which makes me think you might have an old (like 2 days old) version of Constellation.  Some pretty big changes were made to the automatic detection of collections in the last day or two and the new version uses CTRL-C to toggle it on/off (so it can co-exist peacefully with MeteorToys).  If it's still giving this error after a `meteor update`, I'd love to have a repro to help debug.  Thanks for this report, by the way.  Much appreciated.

**Comment by elie222** [comment]
Interesting. I downloaded the latest atmosphere version. I tried ctrl c as
the instructions stated, but only ctrl m worked for me. I'll take a look
again later in the week.

**Comment by JackAdams** [comment]
Weird.  In `.meteor/versions` does it say `constellation:console@1.0.4`?  If not, maybe a `meteor remove constellation:console` followed by a `meteor add constellation:console` and a `meteor update`.  Or you could edit the `.meteor/versions` file manually to make it say `constellation:console@1.0.4`.
